### ISSUE TITLE
Error when there is no data

### ISSUE THREAD

**Issue by alberk8** [Cordobo/angularx-qrcode#1]
Is it possible to initially display that the QR Data is empty.  I am getting error at the console

Error generating QR Code: Empty QR Code data

ngOnInit() { 
 this.QrCode = '';
}

<qrcode [qrdata]="QrCode" [size]="256" [level]="'H'"></qrcode>

**Comment by Cordobo** [comment]
Thanks @alberk8 for your report, I look into it

**Comment by Cordobo** [comment]
Rather than introduce breaking changes into the component, I would check (in your code) if this.QrCode equals an empty string as condition whether to render the component or a placeholder. You can use NgIf to conditionally add or remove the component from the DOM https://angular.io/api/common/NgIf

HTH

**Comment by alberk8** [comment]
Thanks.  I understand your concern on breaking the code.  If possible, please do implement a way where you can allow empty string for the QRCode on the next release.  The reason is that the current code stops/halt when there is a empty string which is a bit of a problem for a newbie.

![image](https://user-images.githubusercontent.com/12510130/32527361-a734d178-c468-11e7-8461-1ae6956a8b9e.png)

My suggestion, is for the default behavior to display an empty QR code with an option to display nothing.  Thank you.

**Comment by Cordobo** [comment]
That's a good argument and it won't break. Feel free to send in an Merge Request or I try to introduce it into the next release.

**Comment by Cordobo** [comment]
Fixed in 1.0.2
