### ISSUE TITLE
Responsive size / scaling and centering?

### ISSUE THREAD

**Issue by HeikoKanzler** [Cordobo/angularx-qrcode#101]
I would like to use the component in a Ionic app.
- how to scale the QR code based on the devices screen width? 

I guess I miss something fundamental, but I had no luck so far.

**Comment by Cordobo** [comment]
Hi @HeikoKanzler 

what did you try so far?

**Comment by Cordobo** [comment]
ping

**Comment by HeikoKanzler** [comment]
Sorry, was away for a while.
I tried different CSS tricks, but at the end it looks like they dont' work as the canvas is rendered after the CSS was applied. I found a work around for now (using the platform width as input width for the canvas)

**Comment by Cordobo** [comment]
Good to hear. I'm closing this.

**Comment by Sarmad-coder** [comment]
I also have the same issue in angular

**Comment by smaniren** [comment]
this worked for me:

``` html
<div class="flex justify-center">
  <qrcode
    class="w-full"
    [qrdata]="myAngularxQrCode"
    [errorCorrectionLevel]="'H'"
    [colorDark]="'#0F172A'"
    [colorLight]="'#F1F5F9'"
    [margin]="0"
    [elementType]="'svg'"
    [allowEmptyString]="true"
    [cssClass]="'[&>svg]:w-full [&>svg]:h-full'"
  ></qrcode>
</div>
```
