### ISSUE TITLE
npm build with error  "Cannot read property 'kind' of undefined"

### ISSUE THREAD

**Issue by zhukongyi** [Cordobo/angularx-qrcode#102]
angularx-qrcode-version:2.1.4
angular-version:8.2+

**Comment by Cordobo** [comment]
Hi @zhukongyi ,

There are similar issues mentioned in issue #67 and #69, please try the workaround and let me know if it worked for you.

**Comment by Cordobo** [comment]
I'm closing this for now, please re-open if you think your issue is not fixed by the workaround.
