### ISSUE TITLE
Suggest to add callback method when scan Barcode

### ISSUE THREAD

**Issue by CharnjeetIotasol** [Cordobo/angularx-qrcode#103]
Can you please add the callback method when someone scan the barcode for showing the loading or processing.

**Comment by Cordobo** [comment]
Hi @CharnjeetIotasol ,

this lib is a QrCode Generator, maybe you afre confusing it with a QrCode Scanner. There is no possibility to check whether the code was scanned or not. I'm closing, please re-open if I'm wrong.
