### ISSUE TITLE
Not working when used with innerHTML

### ISSUE THREAD

**Issue by mwenechac-sys** [Cordobo/angularx-qrcode#108]
I am trying to generate QRcode like so:

html
`<div [innerHTML]="someHtmlCode"></div>`

ts
this.someHtmlCode = ` <qrcode [qrdata]="'some string'" [width]="256" [errorCorrectionLevel]="'M'"></qrcode>`;

But its not working, how can I make it work.?

**Comment by Cordobo** [comment]
Hi @mwenechac-sys 

Can you format your comment in a way that Github can display it? Unfortunately your HTML is not displayed.

**Comment by mwenechac-sys** [comment]
Its formatted now.

**Comment by royaldragonit** [comment]
The same error
