### ISSUE TITLE
Angular optimization warning

### ISSUE THREAD

**Issue by yktoo** [Cordobo/angularx-qrcode#110]
Angular compiler gives the following warning:

```
WARNING in .../node_modules/angularx-qrcode/__ivy_ngcc__/fesm2015/angularx-qrcode.js depends on 'qrcode'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```

Is there anything to do about that?

**Comment by Cordobo** [comment]
Hi @yktoo ,

thanks for your comment, unfortunately there is an open issue in the underlying lib [qrcode](https://github.com/soldair/node-qrcode/issues/236).

The good news is, this is not a big problem, for now it's a warning and your bundle might have some extra bytes.

If you want to get rid of the warning, you can add the following to your `angular.json`:

```
"build": {
  "builder": "@angular-devkit/build-angular:browser",
  "options": {
     "allowedCommonJsDependencies": [
        "angularx-qrcode",
        "qrcode",
     ]
     ...
   }
   ...
},
```

**Comment by mahadihanif** [comment]
add the following to your angular.json:


`"allowedCommonJsDependencies": [
              "angularx-qrcode",
              "qrcode",
              "@cordobo/qrcode"
            ],`

**Comment by Cordobo** [comment]
^^this is now obsolete, as the latest release is re-using the original node-qrcode package.

**Comment by yktoo** [comment]
Indeed, all what's needed as of `angularx-qrcode 15.x` is:

```json
"allowedCommonJsDependencies": ["qrcode"],
```
