### ISSUE TITLE
Create qr code programmatically

### ISSUE THREAD

**Issue by ArkasDev** [Cordobo/angularx-qrcode#111]
So far i only found the possibility to show the qr code via html. To download the qr-code, the generated image must be accessed and saved after rendering the qr-code. In large scale webapps that are use case driven there should be the possibility to generate the qr code programmatically, so that you can generate the qr code so that components can access it via the service e.g. for a download. 

Is there already a suitable option for this use case?

**Comment by KBeDevel** [comment]
I'm not totally sure, but there should be a way to generate a base64 data URI and then allow a download of the file/content (as an alternative to write a file in the server). You will be able to save these data URIs using LocalStorage.

**Comment by Cordobo** [comment]
Hi @ArkasDev 

the underlying lib node-qrcode is capable of creating dataURIs and other "raw" formats like SVG and PNG. From my perspective, this could/should be achieved with a node.js service in the back-end.

I'm closing this issue for now, please feel free to re-open if you think I got you wrong
