### ISSUE TITLE
Angular 11 support

### ISSUE THREAD

**Issue by inexuscore** [Cordobo/angularx-qrcode#112]
Hello,
Thanks a lot for making this repo. Is this actively maintained?
Any plans to update and support Angular 11 any time soon?

**Comment by KingDarBoja** [comment]
I will submit a PR which should support Angular 11.

**Comment by maximodee** [comment]
Currently doesn't appear to be working on Angular 11 so would be great to have a supported version.

**Comment by a1development** [comment]
Support for Angular 11 would be great.

**Comment by AndreasGassmann** [comment]
We're using this library in an angular 11 project that has been updated from angular 9. I'm not seeing any issues. Due to some earlier issues with this library, we set the target to "es5", maybe that's the reason it works? What issues do you guys have?

**Comment by tellybrown** [comment]
> We're using this library in an angular 11 project that has been updated from angular 9. I'm not seeing any issues. Due to some earlier issues with this library, we set the target to "es5", maybe that's the reason it works? What issues do you guys have?

When I upgrade it tells me it isn't supported or something to that effect.  It was many days ago I tried.  I'd be willing to put $10 for it.

**Comment by tellybrown** [comment]
I found that I upgraded incorrectly.  I was on Angular 9 which gave me version 2.3.5.  Once I uninstalled it, I could upgrade angular to 11 and then reinstalled.  Works perfectly.

**Comment by AndreasGassmann** [comment]
@tellybrown What's your build target?

**Comment by tellybrown** [comment]
I am building an IONIC 5 app.

**Comment by AndreasGassmann** [comment]
@tellybrown In your `tsconfig.json`, what's the value of the "target" property?

**Comment by tellybrown** [comment]
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "module": "es2020",
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "lib": [
      "es2018",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true
  }
}

**Comment by mousedownmike** [comment]
I can confirm that `"angularx-qrcode": "10.0.11"` is working with `"@angular/...": "~11.0.5"` and `"@angular/material...":"^11.0.3"`

**tsconfig.json**
```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "module": "es2020",
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "esModuleInterop": true,
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": false,
    "strictInjectionParameters": true
  }
}
```

**Comment by Cordobo** [comment]
Hi @all

thanks for reporting this issue and sorry for the delay, angularx-qrcode@11.0.0 has been released.

Happy coding!
