### ISSUE TITLE
Nested SVG element

### ISSUE THREAD

**Issue by cristianofromagio** [Cordobo/angularx-qrcode#115]
Seems like all element types but SVG get 'directly' appended to the `.qr-code` element. The generated SVG content (which already contains a `svg` element) is appended to another svg element which in turn is appended to the `.qr-code` element. The issue seems to be related to [this line](https://github.com/Cordobo/angularx-qrcode/blob/48c2728489b205938746e09c19bbce6d5ac9077e/projects/angularx-qrcode/src/lib/angularx-qrcode.component.ts#L243).

See a working demo here: [https://stackblitz.com/edit/qr-code-testing](https://stackblitz.com/edit/qr-code-testing?file=src/app/app.component.html)

Images from all element types:

`canvas`
![image](https://user-images.githubusercontent.com/16294559/102086165-658e3600-3df6-11eb-96c2-7ffd70a4ff11.png)

`img`
![image](https://user-images.githubusercontent.com/16294559/102086233-85bdf500-3df6-11eb-9f4d-190d223dc80f.png)

`url` (alias to `img`)
![image](https://user-images.githubusercontent.com/16294559/102086282-9bcbb580-3df6-11eb-944b-b4086842425f.png)

`svg`
![image](https://user-images.githubusercontent.com/16294559/102086363-bdc53800-3df6-11eb-807a-fc65cf2c21c1.png)

**Comment by Cordobo** [comment]
Hi @cristianofromagio 

thanks for reporting the issue, it has been fixed in the latest release 10.0.12

**Comment by cristianofromagio** [comment]
Thanks for the fix!

This also solves a problem where it was not possible to style the component when using SVG (at least I wasn't able to).

Demo:
With [angularx-qrcode@10.0.11](https://stackblitz.com/edit/qr-code-testing?file=src%2Fapp%2Fapp.component.html)
With [angularx-qrcode@10.0.12](https://stackblitz.com/edit/qr-code-testing-10-0-12?file=src%2Fapp%2Fapp.component.html) (same config/style as the other one, just updated the package)
