### ISSUE TITLE
Question: Download QR code as an image 

### ISSUE THREAD

**Issue by charindukavishan** [Cordobo/angularx-qrcode#117]
Is there an API for download QR code as an image in this library?

**Comment by Cordobo** [comment]
Hi @charindukavishan 

thanks for your question. Could you let me know

1) what's the purpose of downloading the image and
2) how's the users process to download the website/app, e.g. clicking on the image or having a separate button "download as image"?

**Comment by charindukavishan** [comment]
1. I want to print the QR code image 
2. Yes. I need to download the QR code image by clicking a separate button
3. I expect a function for download the QR code as an image file (png/jpg)

**Comment by Kytol** [comment]
I'd also like to have QR code downloadable. 

The way I see it is to have QR code available as in typescript side. 
Now I can only access QR code image with 
`<qrcode [qrdata]="'Your data'" [width]="256" [errorCorrectionLevel]="'M'" [elementType]="'svg'"></qrcode>`

Generating QR with this package and downloading with JsPDF (https://www.npmjs.com/package/jspdf) somehow. Currently it works visible in html side, but I don't need users to see QR codes, just download.

**Comment by foramkumar-parekh** [comment]
> 1. I want to print the QR code image
> 2. Yes. I need to download the QR code image by clicking a separate button
> 3. I expect a function for download the QR code as an image file (png/jpg)

Directly download is not available, but you can achieve it using file saver.

this package creates the QR code inside the canvas. so you can 

1. get the canvas element
2. convert it to blob
3. use file saver to save the file

**Comment by charindukavishan** [comment]
thank you for your support :)
