### ISSUE TITLE
ionic 5 & angular 8.1.2 build production error TypeError: Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by KanKai** [Cordobo/angularx-qrcode#118]
ERROR in ./node_modules/angularx-qrcode/fesm2015/angularx-qrcode.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined

**Comment by Cordobo** [comment]
This might be related to #125

I never managed to reproduce the error based on the information provided, so I will closes this issue.

Please reopen if you think this was closed by error and provide a minimalist repo to reproduce. Thanks!
