### ISSUE TITLE
 'const' enums can only be used in property or index access expressions or the right hand side of an import

### ISSUE THREAD

**Issue by shahzaib62342** [Cordobo/angularx-qrcode#122]
`[15:19:05]  typescript: ...ortcut-APP-Basic/node_modules/angularx-qrcode/lib/angularx-qrcode.component.d.ts, line: 17 
            'const' enums can only be used in property or index access expressions or the right hand side of an import 
            declaration or export assignment.`

I'm using `angularx-qrcode@10.0.12` in ionic 3

**Comment by Cordobo** [comment]
Fixed in 12.0.2
