### ISSUE TITLE
I can't upgrade to angular 12

### ISSUE THREAD

**Issue by Caxvalencia** [Cordobo/angularx-qrcode#129]
Peer dependency into package file, didn't let me upgrading to angular version lastest

https://github.com/Cordobo/angularx-qrcode/blob/ff61f4c8bbc6c627f9a715aab0b2d6228c8bb2db/package.json#L29

**Comment by sam-s4s** [comment]
Yes, I had the same sort of thing - had to make sure I installed the newer version of angularx-qrcode before updating angular.

**Comment by megfault** [comment]
I am also stuck on this library for a v12 upgrade. Thankfully this should be solved soon, see PR #132 :fireworks:

**Comment by joewIST** [comment]
any update on this?

**Comment by megfault** [comment]
@Cordobo  Pull request #132 should solve this. Can you please have a look?

**Comment by AbhiThakare** [comment]
Any idea when #132 will merge? please.

**Comment by scifresh** [comment]
I switched to https://github.com/mnahkies/ng-qrcode. It's working fine with Angular 12.

**Comment by timmyrosen** [comment]
> 

Can confirm working with Angular 13 as well!

**Comment by timmyrosen** [comment]
@scifresh Can confirm ng-qrcode is working with Angular 13 as well!

**Comment by Cordobo** [comment]
Version 12 for angular 12 has been released.
