### ISSUE TITLE
CSS class not working on Canvas

### ISSUE THREAD

**Issue by atul4a2l** [Cordobo/angularx-qrcode#133]
I have to add border-radius to QR-code canvas element but it's not working. When i inspect the element from DOM and tried to add CSS there changes reflect.

**Comment by Cordobo** [comment]
Hi @atul4a2l 

I'm a little bit late to the party, but this might help others as well. This is not an issue with angularx-qrcode but rather a general CSS styling thing, I added some sample code for the borderRadius and a button to the demo-app to control this. You can find the code starting with 12.0.3 in `projects/demo-app`.
..
Adding a className to the component with the right styles might fix your issue.

```<qrcode
    [allowEmptyString]="true"
    [className]="yourClassName">
    [elementType]="elementType"
    [errorCorrectionLevel]="errorCorrectionLevel"
    [qrdata]="qrdata"
    [scale]="scale"
    [width]="width"
</qrcode>```

whereas yourClassName is a CSS class:

```
.demoBorderRadius {
  border: dashed;
  border-width: 2px 4px;
  border-radius: 40px;
  overflow: hidden;
}
```

HTH
