### ISSUE TITLE
ansi-regex needs to be updated

### ISSUE THREAD

**Issue by TatianaIvanovaW** [Cordobo/angularx-qrcode#140]
Hello,
ansi-regex cause Moderate vulnerability with the following error:
**Inefficient Regular Expression Complexity in chalk/ansi-regex**
ansi-regex needs to be updated up to version 5.0.1 or higher.
check here for more details: (https://github.com/advisories/GHSA-93q8-gq69-wqmw)

**Comment by michaelbalber** [comment]
A fixed version of qrcode has been released. 
https://github.com/soldair/node-qrcode/issues/278
Will now be possible to use the new version?

**Comment by Cordobo** [comment]
I updated qrcode to the latest version 1.5.0 with the ansi-regex fix included.

There are still vulnerable ansi-regex dependencies in the npm chain, but only in the build and test chain of angular 12.
