### ISSUE TITLE
update to angular v13

### ISSUE THREAD

**Issue by mujahid-akbar** [Cordobo/angularx-qrcode#141]
update peer dependency to angular v13

**Comment by inexuscore** [comment]
Any idea when Angular 13 will be supported? We're trying to update to Angular 13 but a few libraries have conflicting peer dependencies. Thank you very much.

**Comment by specchiasoft** [comment]
Hi i have this error when updating to  "@ubirch/angularx-qrcode": library.

 "@angular/core": "~13.1.1",
 "@ubirch/angularx-qrcode": "^13.0.0",
dev dependencies:
   "@types/qrcode": "1.3.5",
 "typescript": "~4.5.4",



![image](https://user-images.githubusercontent.com/25741411/147405484-d5fcab6f-1045-493a-83f6-59e124eab68d.png)

**Comment by inexuscore** [comment]
**@angular/core** in peer dependencies is targeting > 12 < 13, that's a problem. Is anyone working on this? Unfortunately, I don't have time for submitting a PR at the moment, this is a blocking issue for us trying to upgrade a big project to Angular 13.

**Comment by Cordobo** [comment]
There should be an updated version for angular 13 within the next few hours.

**Comment by inexuscore** [comment]
@Cordobo that's great to hear, awesome news! Thank you very much, much appreciated 🍻

**Comment by specchiasoft** [comment]
> There should be an updated version for angular 13 within the next few hours.

Thank you very mutch

**Comment by Cordobo** [comment]
@inexuscore @specchiasoft 

Hi, sorry for the delay, version 13 for angular 13 has been published right now.

Please let me know, if you experience any issues..

**Comment by inexuscore** [comment]
@Cordobo Hi Cordobo, no problem at all I understand you're busy like everybody else, especially during the holidays. That's awesome! thank you very much, I'll try and update to the latest versions. If I ran into any issues I'll come back with the details. Much appreciated, and happy new year!
