### ISSUE TITLE
How usesvg is use?

### ISSUE THREAD

**Issue by DenWoas** [Cordobo/angularx-qrcode#16]
I am loocking how i can use the attribute usesvg, but I can´t make it work.

Thanks

**Comment by Cordobo** [comment]
Hi DenWoas,

did you set [usesvg]="true" in your code? 

`<qrcode [qrdata]="'Hello'" [size]="256" [level]="'M'" [usesvg]="true"></qrcode>`

**Comment by DenWoas** [comment]
I have achieved it, thanks
