### ISSUE TITLE
Cant use this inside MatDialog

### ISSUE THREAD

**Issue by IvRRimum** [Cordobo/angularx-qrcode#167]
```
    this.dialog.open(DonateModalComponent, {
      data: { address: address },
    });
```
and inside `DonateModalComponent`:
```
<qrcode [qrdata]="'Your data string'" [width]="256" [errorCorrectionLevel]="'M'"></qrcode>
```

```
1. If 'qrcode' is an Angular component, then verify that it is part of this module.
```

It doesnt work only when called from inside `MatDialog`, in regular components, works fine..

**Comment by IvRRimum** [comment]
This is not a public repo :// But i think you should be able to reproduce it

**Comment by FacePalmDev** [comment]
Could reproduce it in a repo as you want help with it?

**Comment by IvRRimum** [comment]
I found a workaround(not too clean): https://stackoverflow.com/questions/59763017/angular-custom-elements-angular-8-material-matdialog-and-matmenu-not-working

The answer to this problem is the question.(Works for me on angular13)

**Comment by FacePalmDev** [comment]
Glad you got to the bottom of it.
