### ISSUE TITLE
Feature Request: Make QR Code downloadable 

### ISSUE THREAD

**Issue by CodeWorldIndustries** [Cordobo/angularx-qrcode#168]
It would be nice if after the QR code was generated, we could some how download it. Maybe consider using file-saver.

**Comment by Cordobo** [comment]
Hi @CodeWorldIndustries 

I think this feature is somehow out of the scope of the lib - but I'm open for PR's.

Otherwise there is a helpful comment (no copy & paste code) from another user with some guidance
https://github.com/Cordobo/angularx-qrcode/issues/117#issuecomment-828166056

HTH
