### ISSUE TITLE
Metadata version mismatch for module ..node_modules/angularx-qrcode/dist/index.d.ts, found version 4, expected 3

### ISSUE THREAD

**Issue by edayan** [Cordobo/angularx-qrcode#17]
I am getting the error:

> Metadata version mismatch for module ..node_modules/angularx-qrcode/dist/index.d.ts, found version 4, expected 3,
> resolving symbol DashboardModule in ../dashboard.module.ts, resolving symbol DashboardModule in ../dashboard.module.ts

my package.json
```
dependencies": {
        "@angular/animations": "^4.4.6",
        "@angular/cdk": "^2.0.0-beta.12",
        "@angular/cli": "^1.7.4",
        "@angular/common": "^4.4.6",
        "@angular/compiler": "^4.4.6",
        "@angular/compiler-cli": "^4.4.6",
        "@angular/core": "^4.4.6",
        "@angular/router": "^4.4.6",
        "angular-mat-datepicker": "0.0.2",
        "angularx-qrcode": "1.0.3"
}
```

and dashboard.module.ts

```
import { QRCodeModule } from 'angularx-qrcode';

@NgModule({
	imports: [
		QRCodeModule
	],

	declarations: [],

	exports: [],

	providers: [],


})
```

**Comment by Cordobo** [comment]
Hello edayan,

thanks for opening a new issue. Could you please provide me with a stripped down version of your app where I can reproduce the error?

Thanks in advance!

**Comment by Cordobo** [comment]
I'm closing this, as not reproducible. Please re-open, if you still encounter the problem.
