### ISSUE TITLE
Error when download QR Code, property parent doesnt exist

### ISSUE THREAD

**Issue by faidancode** [Cordobo/angularx-qrcode#173]
i tried to make download qr code button following this tutorial https://github.com/Cordobo/angularx-qrcode/blob/main/projects/demo-app/src/app/app.component.html. 

`<div class="row row-center row-code">
      <div class="qrcodeImage" *ngIf="qrCode">
        <qrcode
          #parent
          [elementType]="'canvas'"
          errorCorrectionLevel="M"
          [qrdata]="qrCode"
          [width]="240"
        >
        </qrcode>
      </div>
    </div>
    <ion-button class="btn-light" (click)="saveAsImage(parent)"
      >Download QR Code</ion-button
    >`

But it showing error "Property parent doesnt exist on type QrCodePage". Any suggestion?

Thanks in advance.

**Comment by sumegha26** [comment]
@faidancode , I am facing same issue.
How did you resolve it ?

**Comment by Cordobo** [comment]
@faidancode @sumegha26 

Hi there, can you guys provide me with a stripped-down repo here on github where I can reproduce this issue?

**Comment by faidancode** [comment]
@sumegha26 hey, sorry for late response. I found that the cause of the error was the *ngIf="qrCode" condition, when I removed that ngIf, the issue was resolved.
