### ISSUE TITLE
Does imageSrc work on # angular 8 angularx-qrcode@~2.1.4 ??

### ISSUE THREAD

**Issue by biswas-houm** [Cordobo/angularx-qrcode#175]
I gave a path to the image on imageSrc attribute but does not seem to work. Is this possible with 2.1.4?

**Comment by biswas-houm** [comment]
Can we make the imageSrc support on lower versions like 2.14 too?

**Comment by Cordobo** [comment]
@biswas-houm 

yes, this is possible, I'm open for pull requests. If I do it on my own, it'll take some time.

**Comment by adiynsyah** [comment]
hallo @Cordobo  i try in version 11.0.0, i feel my imgSrc is correct path but di qrcode canvas not showing my image

**Comment by adiynsyah** [comment]
> @biswas-houm
> 
> yes, this is possible, I'm open for pull requests. If I do it on my own, it'll take some time.

hallo @Cordobo i try in version 11.0.0, i feel my imgSrc is correct path but di qrcode canvas not showing my image

**Comment by Cordobo** [comment]
When I wrote "this is possible" I referred to the possibility to back-port this feature. It was introduced in version 13 and has been back-ported to version 2.3.7 but not to any other version yet. Sorry for any confusion. As said, I'm open to pull requests to speed the process up a little bit.

**Comment by Cordobo** [comment]
Closed in favor of #183 183
