### ISSUE TITLE
Is there a update for Angular 7 comming?

### ISSUE THREAD

**Issue by ArgV04** [Cordobo/angularx-qrcode#18]
Is there a update for Angular 7 comming? Because during building my app I get the warning:

**_npm WARN angularx-qrcode@1.2.4 requires a peer of @angular/core@^6.0.0 but none is installed. You must install peer dependencies yourself._**

**Comment by Cordobo** [comment]
Hi @ArgV04,

thanks for your feedback, I update the lib at latest this weekend.

**Comment by Cordobo** [comment]
Version 1.3.0 for Angular 7 is available.

via npm
`npm install angularx-qrcode@1.3.0 --save`

via yarn:
`yarn add angularx-qrcode@1.3.0`
