### ISSUE TITLE
Make 2.1.4 version work with ES2015

### ISSUE THREAD

**Issue by KyllVLP** [Cordobo/angularx-qrcode#184]
I'm working on a larger project on an existing website where the ES target cannot be changed. 
I saw this under the known issues and was hoping it could get resolved. 
I've tried using the angularx-qrcode in a local test build in ES5, and it works fine. 
Transpiling to ES2015 gives me the error:
`ERROR in No suitable injection token for parameter 'renderer' of class 'QRCodeComponent'.
no type or decorator`

**Comment by Cordobo** [comment]
Hi @KyllVLP 

thanks for opening this issue. I no longer work with angular 8 so I this might no be of help, but did you try to import from the fesm2015 folder within the angularx-qrcode package?

[fesm2015](https://github.com/Cordobo/angularx-qrcode/blob/559f116b9f2d74fed74b3fba5aea054e0495f0d5/dist/angularx-qrcode/fesm2015/angularx-qrcode.js)

**Comment by Cordobo** [comment]
I'm closing this for now, please re-open if this is still an issue.
