### ISSUE TITLE
content security policies violation issue

### ISSUE THREAD

**Issue by serdec** [Cordobo/angularx-qrcode#196]
# Description

when displaying the qrcode i got an error in the console like the following:

```
Refused to connect to 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAPAAAADwCAYAAAA+VemSAAAAAXNSR0IArs4c6QAAEORJREFUeF7tne1y5UYOQ9fv/9DeyniqxsnYBiiwebulk7/iBwASoq6zW3l7f39//x//oAAKHKnAGwY+cm6ARoFfCmBgFgEFDlYAAx88PKCjAAZmB1DgYAUw8MHDAzoKYGB2AAUOVgADHzw8oKMABmYHUOBgBTDwwcMDOgpgYHYABQ5WAAMfPDygowAGZgdQ4GAFMPDBwwM6CmBgdgAFDlYAAx88PKCjAAZmB1DgYAUw8MHDAzoKYGB2AAUOVgADHzw8oKMABmYHUOBgBTDwwcMDOgpgYHYABQ5WAAMfPDygowAGZgdQ4GAFMPDBwwM6CmBgdgAFDlYAAx88...' 
because it violates the following Content Security Policy directive: "connect-sr..."
```

I presume that this is due to some fetching for the download of the code, would it be possible to add a parameter to skip this?

**Comment by Cordobo** [comment]
Hi @serdec 

first things first, angularx-qrcode does NOT dwnload additional code.

Could you provide me with some addtional data, like your angular version and a strapped-down version of your working code in a repo so I can investigate?

thanks!

**Comment by serdec** [comment]
hi @Cordobo, thanks for your quick reply.

This happens because i have restricted content security policies on my web application like the following

```
`connect-src 'self' 'unsafe-inline'  *.website1.com *.website2.com ... ; ` +
```

these are the errors i get in the console

<img width="639" alt="image" src="https://user-images.githubusercontent.com/1456541/204079498-e3fb8456-384f-4952-8fff-f900c40b3689.png">
<img width="1256" alt="image" src="https://user-images.githubusercontent.com/1456541/204079511-418b8120-6692-4ff1-8ade-8a6d80e1c10f.png">

my code looks like

```js
 <div>
    <div *ngIf="qrCode">
      <qrcode [qrdata]="qrCode" [width]="240" [errorCorrectionLevel]="'M'"></qrcode>
    </div>
 </div>
    
```

where `qrCode = otpauth://totp/testaccount?secret=${secretCode}`

**Comment by Cordobo** [comment]
Hello @serdec 

unfortunately I do not have the time to work on this right now because of my "day job", but I would be more than happy to review and merge a PR.

Feel free to open one with your changes against the development branch.

Thanks
