### ISSUE TITLE
Option to hide title on hover 

### ISSUE THREAD

**Issue by dhyey35** [Cordobo/angularx-qrcode#2]
**Use Case**:

We are displaying QR Code on website and it is going to be scanned by our mobile app. 

**Issue**:

When user hovers over the QR Code on website it displays the JSON data which we have passed in `qrdata` which looks bad for our UX

**Recommended Solution**:

A parameter named `hidetitle` of type `boolean`

**Current Hack**:

Use `pointer-events` property of css and set it to `none`. 

I have reproduced this on [stackblitz](https://stackblitz.com/edit/angular-lda13z?file=app%2Fapp.component.html).

**Comment by Cordobo** [comment]
Hello dhyey35,

and thanks for your report. It's a good enhancement, although I have to hack it into the only dependency of that project:

https://github.com/davidshimjs/qrcodejs/blob/master/qrcode.js#L585

I guess it'll be a **rewrite-to-typescript-project** for the above mentioned lib, I keep you updated of my progress.

**Comment by dhyey35** [comment]
I think rewrite would be an overkill as the project hasn't been updated since 2015, we can just fork it and add a new option called `noTitle` in `_htOption` which would be a boolean on https://github.com/davidshimjs/qrcodejs/blob/master/qrcode.js#L536 and pass it to `makeCode` from https://github.com/davidshimjs/qrcodejs/blob/master/qrcode.js#L572 than we can have a simple `if` condition check in `makeCode` function in https://github.com/davidshimjs/qrcodejs/blob/master/qrcode.js#L585 and just update our [qrcodejs2.d.ts](https://github.com/Cordobo/angularx-qrcode/blob/master/src/components/angularx-qrcode/qrcodejs2.d.ts) and finally point our `package.json` to our forked version.

What do you think about this ?

**Comment by Cordobo** [comment]
That's the most pragmatic solution, that's the way to go.

**Comment by maksof-Rehan** [comment]
@GianniAzizi  nice tip

**Comment by theshreyansh** [comment]
google a lot on this, and finally, find below piece of code working,
use > style="pointer-events: none"
Example >
<div class="qrscan">
<qrcode [qrdata]="angularxQrCode" style="pointer-events: none" [size]="150" [level]="M"></qrcode>
</div>

**Comment by theshreyansh** [comment]
qrcode [qrdata]="angularxQrCode" style="pointer-events: none" [size]="150" [level]="'M'" ></qrcode

**Comment by Yorer** [comment]
> [attr.title]="''"

This helped thanks ;)

**Comment by HasithNawana** [comment]
> google a lot on this, and finally, find below piece of code working,
> use > style="pointer-events: none"
> Example >

Thanks a lot

**Comment by Junior0909** [comment]
I have to add [attr.title]="''" on the component html tag.But it doesn't work,then try another style="pointer-events: none", it's OK. I think it wasn't the best.

**Comment by eliasdev** [comment]
> I have to add [attr.title]="''" on the component html tag.But it doesn't work,then try another style="pointer-events: none", it's OK. I think it wasn't the best.

But it does the job, I had to go with this one as well.
