### ISSUE TITLE
Question: Why use qrcodejs2?

### ISSUE THREAD

**Issue by choopage** [Cordobo/angularx-qrcode#20]
The current dependency is qrcodejs2 which is maintained about 3 years ago. I suggest using node-qrcode package. https://github.com/soldair/node-qrcode 

Because it is actively maintained.

**Comment by Cordobo** [comment]
Hi, thanks for the suggestion, I look into it

**Comment by choopage** [comment]
Hi @Cordobo 

Is there any chance for this to happen?

Thanks.

**Comment by Cordobo** [comment]
Hi choopage,

definitely yes, I evaluate a couple of qrcode libs for a 2.0 release

**Comment by mpgo13** [comment]
This issue would probably solve #22

**Comment by Cordobo** [comment]
Superseded by https://github.com/Cordobo/angularx-qrcode/issues/53
