### ISSUE TITLE
Replace qrcode library to fix commonjs warning

### ISSUE THREAD

**Issue by iCodr8** [Cordobo/angularx-qrcode#202]
[webpack-dev-server] WARNING
.../node_modules/angularx-qrcode/fesm2020/angularx-qrcode.mjs depends on 'qrcode'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
logger @ index.js:556
(anonymous) @ index.js:730
warn @ index.js:189
warnings @ index.js:247
(anonymous) @ socket.js:60
client.onmessage @ WebSocketClient.js:50
Show 6 more frames

**Comment by Cordobo** [comment]
@iCodr8 

I hope the workaround provided by @eXpertise7 helped you.

I'm closing this for now, please re-open if this is still an issue.

**Comment by de-don** [comment]
This is not fixing the issue, this is just disables it. I think it's better to try to remove qrcode library from deps to remove this warning and provide better optimization.
