### ISSUE TITLE
angularx-qrcode > @cordobo/qrcode@1.5.0: Package no longer supported

### ISSUE THREAD

**Issue by eXpertise7** [Cordobo/angularx-qrcode#203]
Hi maintainers,

Question about this:

![cordobo qrcode package no longer supported](https://user-images.githubusercontent.com/17203747/214071438-e8a86353-7547-4e3b-888f-6ad50505386a.PNG)

What's going on with dependency  of your package (@corobo/qrcode@1.5.0):

https://www.npmjs.com/package/@cordobo/qrcode

It's not being maintained, will it affect this library also?

My Team is using this library in Production so I'd like to prepare for the future. Thanks for the response in advance.

@Cordobo 

Kind regards,
Robert Medved

**Comment by Cordobo** [comment]
Hi @eXpertise7 

TLDR;
You can safely use angularx-qrcode lib, it's actively maintained and not deprecated.
@cordobo/qrcode is a support library for angularx-qrcode and contained a fix for node-qrcode. Node-qrcode had an issue with the lib colors.js and as they couldn't update the lib in time, we made the decision to fork their lib and fix it.

Node-qrcode has fixed this issue for a while now. We then deprecated our fork and reverted to the original lib with angurlarx-qrcode.

Long version:
https://github.com/Cordobo/angularx-qrcode/issues/155
