### ISSUE TITLE
qrCode not working in dialog window!

### ISSUE THREAD

**Issue by funrockmedia** [Cordobo/angularx-qrcode#209]
qrCode not working in dialog window, anyone have experiences this issue? or am I doing something wrong
Same code working when it's not a dialog window.

**Comment by xC0der** [comment]
I use the QR code in a dialog window without issues using Angular, and Angular material 15.

**Comment by sam-s4s** [comment]
I am also using QRCodes in dialogs - but then, what is your definition of a dialog? :)

A dialog is probably just a div tag on top of your page, right? Maybe it's a z-index issue?

**Comment by biel-correa** [comment]
@funrockmedia please provide some code

**Comment by Cordobo** [comment]
I'm closing this, but please feel free to re-open and add some code for context.
