### ISSUE TITLE
Support for Angular 16

### ISSUE THREAD

**Issue by igorosabel** [Cordobo/angularx-qrcode#214]
Hi!

Angular 16 was released yesterday, please update to give support to this new version.

Thanks

**Comment by Cordobo** [comment]
#215

**Comment by Cordobo** [comment]
Thanks to @gerd-siebert for his pull request!

**Comment by Cordobo** [comment]
@igorosabel Please let us know if it works for you, and if so, feel free to close the issue.

**Comment by igorosabel** [comment]
I just tried and it works perfectly, thank you very much for the quick response.
