### ISSUE TITLE
Angular 4 - Cannot read property '_android' of undefined

### ISSUE THREAD

**Issue by elaineyl** [Cordobo/angularx-qrcode#22]
Error (Cannot read property '_android' of undefined) is returned in /qrcodejs2/qrcode.js:

if (this._android && this._android <= 2.1) {
...
}

**Comment by Cordobo** [comment]
Could you please provide a stripped down sample repo?

**Comment by mpgo13** [comment]
Ran into the same issue with Angular 8 today.

Steps to reproduce:

1. Clone https://github.com/mpgo13/angular8-angularx-qrcode
2. Run `ng build`
3. Run `cd dist/angular8 && python -m SimpleHTTPServer`
4. Browse to http://localhost:8000

Expected Result:
 - QRCode visible
Actual Result:
 - Script error as [commented above](https://github.com/Cordobo/angularx-qrcode/issues/22#issue-387629479)

Note: Not reproducable with angular's dev server (`ng serve`)

**Comment by Cordobo** [comment]
Hi @mpgo13, thanks for your sample Repo, I have a look into it.

**Comment by mpgo13** [comment]
Seems like `qrcode.js` gets loaded in strict mode. I opened an issue: https://github.com/angular/angular/issues/30759

**Comment by Cordobo** [comment]
Hi @mpgo13 thanks for your minimal repo, I get this fixed as soon as possible.

**Comment by Cordobo** [comment]
A temporary workaround is to set the target in your tsconfig.json from es2015 to es5:

`"target": "es5"`

Source: https://github.com/angular/angular/issues/30759#issuecomment-497636172

**Comment by mmarcks** [comment]
Hi @Cordobo, I've had this error and when searching the topic I ran into an interesting article:
[https://github.com/davidshimjs/qrcodejs/pull/114/files]

Don't know if you've seen it but hope this helps you find a solution.

**Comment by Yorer** [comment]
I've updated my tsconfig.json, this is working for me:
`"target": "es5"`

I've used es2015 before.
