### ISSUE TITLE
Is it possible to get the Base64 image string for a QR code in a TS file?

### ISSUE THREAD

**Issue by 0xFACE** [Cordobo/angularx-qrcode#225]
Not issue, but general question.
I would like to use angularx-qrcode in a Angular service, without html template. Is it possible to get the Base64 image string for a QR code in a TS file?

**Comment by Sikachyna** [comment]
I'm interested in this way also.

**Comment by 0xFACE** [comment]
I fund this package: jspdf-barcode https://github.com/castrix/jspdf-barcode. 
It can be used directly in jspdf class, without rendering the code in the html element.
But currently supports  only Code-128 barcode.

**Comment by Cordobo** [comment]
Sorry for the late reply, I was on vacation. You might use node-qrcode, the underlying lib of angularx-qrcode, directly in your project.

HTH
