### ISSUE TITLE
Support for Angular 17

### ISSUE THREAD

**Issue by Alvaro948** [Cordobo/angularx-qrcode#231]
Hi,

Today has been released Angular 17, can you increment the peer dependencies range to support this version?

https://blog.angular.io/introducing-angular-v17-4d7033312e4b

Thanks for your work!

Just in case anyone needs to update, by forcing the installation it should work

```bash
npm install --force
```

Please, avoid comments like "+1", it sends a notification to anyone subscribed

**Comment by pil78** [comment]
+1

**Comment by John-Santacruz** [comment]
Hi, 

Please make this also compatible for angular V17

**Comment by StefanoVe** [comment]
+1

**Comment by 0xFACE** [comment]
+1

**Comment by jase88** [comment]
Alternative to `force` flag in `package.json`:

```json
{
  // ...
  "overrides": {
    "angularx-qrcode": {
      "@angular/core": "$@angular/core"
    }
  }
}

```

**Comment by Muehli25** [comment]
#232 I created a PR for that!

**Comment by igorosabel** [comment]
Any news? @Muehli25 's PR should do it

**Comment by LeroyGerrits** [comment]
+1

**Comment by Cordobo** [comment]
Hi @all,

thanks to @Muehli25  for his work on the upgrade for angular 17 and sorry for the delay.

Let me know, if the latest version works for you
