### ISSUE TITLE
Support qrCodeURL (EventEmitter) for 12.0.3 version

### ISSUE THREAD

**Issue by Persivan** [Cordobo/angularx-qrcode#233]
Sad. Version "^12" doesn't have qrCodeURL in QRCodeComponent. 
Temporary solution: use version ^13 instead of ^12."

**Comment by Cordobo** [comment]
I close the issue and we should leave it here as workaround for others, but it's very unlikely that version 12 will get any update if it's not from the community.

Feel free to re-open, if you think you might contribute code for the older release.
