### ISSUE TITLE
Support generate url in QR Code

### ISSUE THREAD

**Issue by tuananhsmart17** [Cordobo/angularx-qrcode#24]
Hi. This is great package. I want to generate url and when anyone scan it, will be open browser with url. I like this package , very helpful and support ssr. Thanks you

**Comment by Cordobo** [comment]
Hi @tuananhsmart17 ,

that's exactly what this library does. It generates QR-Codes from strings. These strings can be of any type (or content), and of cause URLs too. Your client is responsible what it does with the information from the QR-Code.

A stripped down sample implementation can be found here:
https://github.com/Cordobo/angularx-qrcode-sample-app

I close the issue, please reopen if you found your issue to be unsolved.

HTH
