### ISSUE TITLE
qrcode module is not ESM

### ISSUE THREAD

**Issue by caboodal** [Cordobo/angularx-qrcode#250]
When building I receive the following warning...

[WARNING] Module 'qrcode' used by 'node_modules/angularx-qrcode/fesm2022/angularx-qrcode.mjs' is not ESM

Should I expect this, obviously I can override it in the angular.json file but I'd prefer not to.

**Comment by Cordobo** [comment]
Hi @caboodal 

thanks for your contribution, unfortunately it#s an issue with the underlying lib, I commented in issue #110 with more detail.

I'm closing this, as duplicate
