### ISSUE TITLE
Please add support for Angular v18

### ISSUE THREAD

**Issue by woutersteven** [Cordobo/angularx-qrcode#251]
Angular 18 has been released, please consider adding support for Angular 18

**Comment by themrdanielvp** [comment]
Is there any timeline for when this will be updated for Angular 18?

**Comment by born2net** [comment]
yes please, need to move to ngv18 and waiting on this lib <3 TX!

**Comment by igorosabel** [comment]
Any updates? I know I can force or override, but I prefer to have a "stable" version.

Thanks!

**Comment by koddr** [comment]
Any updates? 🤔

Would be great to have a new version with Angular 18 support.

**Comment by caboodal** [comment]
Is this project ceased to be supported?

**Comment by henkkelder** [comment]
@Cordobo @igorosabel 

Hey could you please accept the PR of allows others to do so?

**Comment by Roxcsas** [comment]
Any updates?

**Comment by henkkelder** [comment]
Thank you

**Comment by anders8** [comment]
Thanks! Was getting worried about you... nearly called Germany!
