### ISSUE TITLE
Do you think it is possible to add support for downloading the qr with an icon that has been entered with url? 

### ISSUE THREAD

**Issue by DIKGONZA** [Cordobo/angularx-qrcode#260]
It only allows to download if the image is in the project assets, but if you put the image with a url it doesn't download it. 

![image](https://github.com/user-attachments/assets/02f9bdbd-eb77-44f6-bf71-ce7642844c39)

https://stackblitz.com/edit/stackblitz-starters-dy21ym?file=src%2Fmain.ts

Thanks you

**Comment by amazing4u** [comment]
@DIKGONZA @Cordobo I fixed this and created a pull request for this

**Comment by Cordobo** [comment]
Merged and released as 18.0.2

@amazing4u thanks for the pull request 👍
