### ISSUE TITLE
Nice web-based solution

### ISSUE THREAD

**Issue by professor-rage** [Cordobo/angularx-qrcode#263]
I tried the angular 17 version but [scale] in directive mode does not work. The dot scale remains the same regardless of number entered. 

Browser: Google Chrome 129.x 

<qrcode [qrdata]="'Your data string'" [width]="256" [scale]="1" [errorCorrectionLevel]="'M'"></qrcode>

Any guidance is greatly appreciated.

Thanks,
Dean 
[https://tapple.io](https://tapple.io)

**Comment by Cordobo** [comment]
Hi @professor-rage 

The scale factor works when the width is set to 10 (default)

  <qrcode
    [qrdata]="'https://github.com/Cordobo/angularx-qrcode'"
    [allowEmptyString]="true"
    [ariaLabel]="'QR Code image with the following content...'"
    [cssClass]="'center'"
    [colorDark]="'#000000ff'"
    [colorLight]="'#ffffffff'"
    [elementType]="'canvas'"
    [errorCorrectionLevel]="'M'"
    [imageSrc]="'./assets/angular-logo.png'"
    [imageHeight]="75"
    [imageWidth]="75"
    [scale]="32"
    [title]="'A custom title attribute'"
    [width]="10"
  ></qrcode>
  
  You can play around with the values here
  https://cordobo.github.io/angularx-qrcode/

**Comment by professor-rage** [comment]
Perfect. Thank you.
