### ISSUE TITLE
Support for Angular v19

### ISSUE THREAD

**Issue by Cordobo** [Cordobo/angularx-qrcode#266]
Angular 19 is coming out soon! 🎉

This issue is here to keep track of the progress on adding Angular 19 support to angularx-qrcode.

**Comment by igorosabel** [comment]
Hi! Angular 19 was realeased a couple days ago. Waiting for your update :) thanks!

**Comment by Cordobo** [comment]
angularx-qrcode 19 for angular 19 is out.
[angularx-qrcode @ npm ](https://www.npmjs.com/package/angularx-qrcode)

If you are upgrading from angularx-qrcode 18 or earlier, please

Since Angular 19, the latest version of the angularx-qrcode module is now exported as a standalone component. If you’re upgrading from a version before Angular 19, please replace the import statement with the component’s name since it’s now a standalone component. Instead of importing `QRCodeModule` we import `QRCodeComponent`.

```
# OLD - angular 18 and older
# File: app.module.ts
import { QRCodeModule } from 'angularx-qrcode';

# NEW - angular 19 and newer
// File: app.component.ts
import { QRCodeComponent } from 'angularx-qrcode';
```

Thanks for using angularx-qrcode and happy coding 🎉
