### ISSUE TITLE
Update peer dependencies for NG 7.2.2

### ISSUE THREAD

**Issue by MikeOne** [Cordobo/angularx-qrcode#27]
Trying to install Angular 7.2.2 - failing to due peer dependency issue:

Package "angularx-qrcode" has an incompatible peer dependency to "@angular/core" (requires ">= 5.0.0 <= 7.2.0" (extended), would install "7.2.2").

I have 1.5.1 already installed.

**Comment by MikeOne** [comment]
I see there is already a PR for this (#26) - can this please be merged?

**Comment by Cordobo** [comment]
Fixed for version 1.5.2 with PR #28.
