### ISSUE TITLE
not able to read the string data (qrdata) when size is set less than 100 

### ISSUE THREAD

**Issue by AngularTx** [Cordobo/angularx-qrcode#31]
Hi, 

Very good package ! 
Have some issues or need help in understanding the correct usage of this package. Not much detailed explanation are given on the options . 

1) 
When reducing the size to less than 100 , sometimes the scanner is not able to get the required data . 
but when i keep the size as 100 or more  , I have no issues in getting the text. Anything less than 100 , takes lot of time and nothing returns(sometimes a no is returned) .

My application also will be used on mobile phones. So sometimes the text is not displayed when using the scanner . 

My text content is around 200 to 300 chars . 

Also the level usage needs to be elaborated , so we can use it accordingly. For now i use the level as L. 

Is there any 1 to 1 relation between size and the text data ? 
Level usage 
When screen size is reduced/compressed , the scanner is not able to get the text and returns just a number .

**Comment by Cordobo** [comment]
Hi @AngularTx 

I wrote about it a while ago here https://stackoverflow.com/a/49667939

> QR Codes have a limited 'volume' to store data, and the available space is narrowed by the actual size of your canvas, the correction level and used QR Code version [Ref]
> 
> The angularx-qrcode lib comes with sensible defaults (size of 256 x 256px, error correction level 'm') to store your data. A size of 150 x 150px can only hold ~1/3 of the libs default.
> 
> To get more storage space, you may increase the possible amount of data stored in your QR code with these two options:
> 
>     Increase the canvas-size to 256px and resize your canvas with CSS to 150px
> 
>     lower the correction level
> 
> Both options are fine in a digital environment where we rarely encounter issues with loss or dirt.
> 
> Sample (for angularx-qrcode):
> 
> <qrcode [qrdata]="myAngularxQrCode" [size]="256" [level]="'L'"></qrcode>

Did you try to raise the size and scale the generated QR-Code via CSS?
