### ISSUE TITLE
mark qrdata strict as text or url 

### ISSUE THREAD

**Issue by AngularTx** [Cordobo/angularx-qrcode#32]
I have created an object which would have 
data = { "endpoint": https://abc/123?123=123;"abc":https://abc/123 } . I would show it as a string! 

On android apps scanners - I see it shows as text only .
On iphone - we see it is considered as a URL and opens in browser.

**Comment by Cordobo** [comment]
@AngularTx 

I hope I get you right, did you try to wrap JSON.stringify() around your data? It should be treated as a string as expected.
