### ISSUE TITLE
Export image/pdf

### ISSUE THREAD

**Issue by Danieleeee** [Cordobo/angularx-qrcode#37]
Hi,
is possible to export qrCode as image or pdf?

Thanks

**Comment by Cordobo** [comment]
@Danieleeee 

it depends, you can generate an SVG setting the attribute usesvg to true
`<qrcode` [qrdata]="myAngularxQrCode" [size]="256" [level]="'M'" usesvg="true"></qrcode>

and reuse the SVG programatically from within your code to generate other image formats or PDFs.

Creating PDFs directly is out of scope of this lib.
