### ISSUE TITLE
Created Qr code having data as Json (did json.stringify too) but cannot get scanned somehow

### ISSUE THREAD

**Issue by PradneshShinde** [Cordobo/angularx-qrcode#44]

**Comment by Cordobo** [comment]
Hi Pradnesh,

I can only guess what could be the issue, but here are my ideas

1. An issue with your QR-Code reader (clearly out of the libraries scope, the right place to ask would be a site like stackoverflow)
2. A QR code has a maximum payload which size is limited by several parameters:

- size
- level

If your size and level are too small for the string you added to "qrdata", the resulting QR Code only uses a part of your data and an error occurs.

Please try to adjust both parameters until the builtin camera from iOS or android can read your data.

HTH
