### ISSUE TITLE
Reloading qrcode with wrong params

### ISSUE THREAD

**Issue by gkucmierz** [Cordobo/angularx-qrcode#45]
Qrcode is opening with parameters of another qrcode used in app.

In first view I am displaying canvas qrcode:
![Zrzut ekranu 2019-04-17 o 15 18 53](https://user-images.githubusercontent.com/739084/56290810-3fe1f280-6124-11e9-9369-77a2843bf707.png)

Then when I open modal I prefer to have svg here:
![Zrzut ekranu 2019-04-17 o 15 19 02](https://user-images.githubusercontent.com/739084/56290847-5a1bd080-6124-11e9-8487-c091964d1c03.png)

Then after closing modal, changing route and going back to route with qr code it inherits usesvg option somehow from modal view:
![Zrzut ekranu 2019-04-17 o 15 19 18](https://user-images.githubusercontent.com/739084/56290899-76b80880-6124-11e9-9917-cad054d6b491.png)

But it should not:
![Zrzut ekranu 2019-04-17 o 15 21 35](https://user-images.githubusercontent.com/739084/56290936-86cfe800-6124-11e9-8a00-ddb851a47992.png)

**Comment by Cordobo** [comment]
@gkucmierz Can you provide me a stripped down working repo here on gitlab?
