### ISSUE TITLE
Angular 8 support

### ISSUE THREAD

**Issue by mrjoedang** [Cordobo/angularx-qrcode#47]
```
warning " > angularx-qrcode@1.5.3" has incorrect peer dependency "@angular/common@^6.0.0-rc.0 || ^6.0.0".
warning " > angularx-qrcode@1.5.3" has incorrect peer dependency "@angular/core@^6.0.0-rc.0 || ^6.0.0".
```

**Comment by nevernet** [comment]
```
npm WARN angularx-qrcode@1.5.3 requires a peer of @angular/common@>= 5.0.0 < 7.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN angularx-qrcode@1.5.3 requires a peer of @angular/core@>= 5.0.0 < 7.3.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by Yoda6** [comment]
👍

**Comment by Cordobo** [comment]
Hi there, short notice, I'm working on a it.

Related issues are: #22 #46

**Comment by Cordobo** [comment]
Short update:

I will update Angular 8 Support with the next release (1.6.0).

In 1.6.x you will need the following temporary workaround: Set the target in your tsconfig.json from es2015 to es5:

`"target": "es5"`

Source: https://github.com/angular/angular/issues/30759#issuecomment-497636172

**Comment by Cordobo** [comment]
Version 1.6.0 has been released (and needs the workaround from above). I'm working on version 2 of angularx-qrcode which makes this obsolete. Closing this.

**Comment by nevernet** [comment]
Great

**Comment by robinmanuelthiel** [comment]
@Cordobo, what is the best way to get notified, when the new version that does not require the workaround comes out? is there an open issue for that, which i can follow?

**Comment by Cordobo** [comment]
@robinmanuelthiel

Good question, I added a new issue to follow up:
https://github.com/Cordobo/angularx-qrcode/issues/53
