### ISSUE TITLE
doesn't work with ng build or ng build --prod

### ISSUE THREAD

**Issue by harkal18** [Cordobo/angularx-qrcode#49]
this lib is amazing 
i coded all my stuff and everything worked fine till the time i was testing on localhost
so after finishing my code i deployed my app to website and it doesn't work there 
and no errors in console

following are my code work space configurations

`Angular CLI: 7.3.9
Node: 8.12.0
OS: win32 x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cli                      7.3.9
@angular/fire                     5.2.1
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0`

**Comment by Cordobo** [comment]
Hi @harkal18 , glad you like the lib. I'm working on the fix for Angular 8+.

Did you try this temporary workaround? Set the target in your tsconfig.json from es2015 to es5:

`"target": "es5"`

Source: https://github.com/angular/angular/issues/30759#issuecomment-497636172

**Comment by harkal18** [comment]
thats ok
but why does it work in localhost then ?

**Comment by harkal18** [comment]
it still doesn't work bro
i haven't changed anything in my project and just now i looked at my tsconfig.json
this is how it looks
`{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "es2015",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ]
  }
}
`

it looks adjactly how you want it
target set to es5

**Comment by Cordobo** [comment]
I created a sample repo for Angular 8 here: https://github.com/Cordobo/angularx-qrcode-sample-app

The only difference I see is ```"module": "es2015",```, whereas my tsconfig.json states ```"module": "esnext",``` (although both worked in my test)

The following is just to be sure, we both have the same setup:
0. Checkout the sample-repo 
1. Run ```npm install```(or remove all npm modules and reinstall)
2. Run ```ng build``` again
3. Run ```npm run dev``` to start up a local server for your production-build

**Comment by bkimminich** [comment]
I am using `^1.6.0` which compiles with both `es5` and `es2015` without problems. But when loading the application with `es2015`-compiled code I get this error:

![image](https://user-images.githubusercontent.com/3531020/60058962-b97cfa80-96ea-11e9-88f6-6589d2582358.png)

**Comment by Cordobo** [comment]
Hi @bkimminich , I'm actively working on a version without this error, meanwhile a temporary workaround has to be applied, es2015 as target does not work yet for production builds, see here:

https://github.com/Cordobo/angularx-qrcode#install-160-with-angular-8

You could although checkout the sample repo from above, which doesn't throw the ```this._android``` error with angular 8.

HTH

**Comment by frabanca** [comment]
Same problem here. 

```
   _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.0.3
Node: 10.12.0
OS: win32 x64
Angular: 8.0.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.3
@angular-devkit/build-angular     0.800.3
@angular-devkit/build-optimizer   0.800.3
@angular-devkit/build-webpack     0.800.3
@angular-devkit/core              8.0.3
@angular-devkit/schematics        8.0.3
@angular/cli                      8.0.3
@ngtools/webpack                  8.0.3
@schematics/angular               8.0.3
@schematics/update                0.800.3
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0
```

```
Uncaught TypeError: Cannot read property '_android' of undefined
```


tsconfig.json
```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "esnext",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ]
  }
}

```

**Comment by Cordobo** [comment]
Hi @frabanca,

Please use the [workaround](https://github.com/Cordobo/angularx-qrcode#install-160-with-angular-8) mentioned above until a refactored version is available:

Replace:
`"target": "es2015"`
with
`"target": "es5"`

Closing this, as I'm actively working on this.

**Comment by anantanandgupta** [comment]
Hi @Cordobo, I have been waiting for this path since long time now. Can you please help us with the fix. By the way Angular 9 is on the edges to get released.
