### ISSUE TITLE
Template Parse error

### ISSUE THREAD

**Issue by ovesyan19** [Cordobo/angularx-qrcode#51]
Hi @Cordobo ! I'm trying to add library to my project. I've installed it and then imported to module where my component lives but I still have template parse errors like this

compiler.js:2430 Uncaught Error: Template parse errors:
Can't bind to 'qrdata' since it isn't a known property of 'qrcode'.

Angular version: 7.2.15

**Comment by Cordobo** [comment]
Hi @ovesyan19 ,

can you provide a stripped down sample repo to reproduce the error?

**Comment by ovesyan19** [comment]
@Cordobo yeah, I've put saple code in Stackblitz to check if it's working and no problems with that, but I'm pretty curious what can be wrong in mine if it's only importing of module to set it up. unfortunately I cant provide repo. if you can suggest cases which can cause this behavior, I will be very thankful

**Comment by ovesyan19** [comment]
@Cordobo I've found what caused this issue. I've imported qrcode module only in one module where my Testcomponent lives, but few other components inherit from Testcomponent, so I just add to their module qrcode too and now it's working. maybe it will be helpful for someone

**Comment by Cordobo** [comment]
Thanks for your feedback!
