### ISSUE TITLE
Angular v8.1.x support

### ISSUE THREAD

**Issue by lukengda** [Cordobo/angularx-qrcode#52]
The Angular 8.1 release is not supported by the peerDependency settings:

`Package "angularx-qrcode" has an incompatible peer dependency to "@angular/common" (requires ">= 5.0.0 < 8.1.0", would install "8.1.2")`

Could we set it to `">= 5.0.0 < 9"` to not warn for 8.x releases or is there some work for further support to do?

**Comment by Cordobo** [comment]
@lukengda

Version 1.6.2 has been published with fixed peer dependencies ( angular < 9 )

Please close this issue, if it works for you.

Thanks for contributing

**Comment by lukengda** [comment]
Thanks for the quick reaction! Installs now without warnings.
