### ISSUE TITLE
Angular 8+ es2015 support (qrcode rewrite)

### ISSUE THREAD

**Issue by Cordobo** [Cordobo/angularx-qrcode#53]
Hi there,

I open this issue to keep you updated about my ongoing efforts to provide es2015 support for Angular 8+.

Angular 8 changed the default target in tsconfig.json from es5 to es2015, which resulted in a build error when building with ng build (ng serve works as expected).

To follow the efforts, subscribe to this issue, I will update it from time to time.

**Update 3: 29/12/2019 (29. Dec. 2019)**

### Version 2.0.0 is now available

Version 2.0.0 is now available for download and fixes the es5 issue in Angular 8+. A workaround is no longer needed.

TODOS:
- [x] DONE: Update Documentation to reflect the changes
- [x] DONE: Add a step-by-step guide to migrate from 1.x to 2.x
- [ ] TBD: Test against angular 9
- [ ] TBD: Test against Ivy compiler
- [ ] TBD: Update Demo App
- [ ] TBD: Install a working demo app

**Update 2: 29/12/2019 (29. Dec. 2019)**

I finished the transition to the new qrcode library and released a series of 2.0 alpha versions to npm. The code is still WIP, the API is not feature complete and there are a couple of breaking changes due to the underlying lib.

**Update 1: 09/02/2019 (2. Sep. 2019)**

I'm now working in my spare time for a while on a recursion error in the lib. I push my branch to github when this issue is fixed.

### Workaround (no longer needed)

A temporary workaround is to set the target in your tsconfig.json from es2015 to es5:

`"target": "es5"`

**Comment by lukengda** [comment]
Do you accept contributions for parts of the workload once you have a good plan for v2?

**Comment by Cordobo** [comment]
@lukengda support is always welcome, I keep you (and any other interested) updated

**Comment by acp9191** [comment]
Any update on this? Would really love to set my target back to es2015.

**Comment by PaLaMuNDeR** [comment]
Since we are on that topic:
`"target": "es6"`
also doesn't work

**Comment by bmesin** [comment]
@Cordobo 
Are there any news here maybe? 
Uncaught TypeError: Cannot read property '_android' of undefined #14889

This is still happening in Angular 8

**Comment by Cordobo** [comment]
@bmesin The workaround still needs to be applied.

**Comment by garysb** [comment]
Having the same issue:

Uncaught TypeError: Cannot read property '_android' of undefined

**Comment by Cordobo** [comment]
@garysb Please use my workaround from above

**Comment by Zattor** [comment]
Hi, is it fixed? I tried to add it in a project where I cannot change the lib to es5 and as you mentioned, the workaround is probably needed to fix the "_android undefined" error.

**Comment by songokudbz** [comment]
Waiting ...

**Comment by egodefroy** [comment]
Not willing to had stress for you but going back to es5 brought me into trouble elsewhere. I like your solution and I'm waiting for a solution or production work-around in es2015... Cheers

**Comment by Cordobo** [comment]
@egodefroy I came up with another workaround in the lib itself. I give it a try this weekend and I hope I can ship a new pre-2 version with es2015 support.

**Comment by songokudbz** [comment]
Does the latest beta version contain this fix?

**Comment by Slash7GNR** [comment]
Any news ? I would also like to use the package but I can't turn to ES5

**Comment by Cordobo** [comment]
> Does the latest beta version contain this fix?

No, th elatest bete is more of a WIP and shouldn't be used (it'll break your build)

**Comment by choopage** [comment]
@Cordobo thank you for maintaining this package. And for using https://github.com/soldair/node-qrcode in your rewrite. Appreciate your effort! Thank you!

**Comment by songokudbz** [comment]
> @egodefroy I came up with another workaround in the lib itself. I give it a try this weekend and I hope I can ship a new pre-2 version with es2015 support.

It has been already more than 30 days. Can you give us a status update please?

**Comment by songokudbz** [comment]
All I want for Christmas is .... for this fix to be made available .... 🎄

**Comment by Cordobo** [comment]
> All I want for Christmas is .... for this fix to be made available .... 🎄

Sorry, I couldn't make that wish come true...

But, as of today, there is a working 2.0.0-alpha.1 published to npm (see my update above). Please do not expect too much, it does not break, it displays QR codes (as expected), but the API is not feature complete and there are no Docs available yet.

**Comment by Cordobo** [comment]
Tada, Version 2.0.0 is out - thank my wife and my newborn son :)
