### ISSUE TITLE
Aling

### ISSUE THREAD

**Issue by mvaipa** [Cordobo/angularx-qrcode#56]
Aling qrcode center page?

**Comment by Cordobo** [comment]
@mvaipa you can put it into a div-container and add css to align it. Please have a look at the demo repo or for general questions about css visit https://developer.mozilla.org/en-US/

**Comment by ezequiel88** [comment]
view.html

```
  <div class="qrcodeBox">
    <qrcode [qrdata]="qrcode" [width]="200" [elementType]="svg"></qrcode>
  </div>
```

style.css
```
.qrcodeBox {
    display: flex;
    flex-direction: row;
    flex-wrap: nowrap;
    justify-content: center;
    align-items: center;
}
```
