### ISSUE TITLE
Dynamic update qr value string

### ISSUE THREAD

**Issue by MuruganLR** [Cordobo/angularx-qrcode#6]
While i'm updating the qr value dynamically, it is not updating. It takes old values only what I have initiated.

**Comment by SaloniArora21** [comment]
I am also facing this issue. I am passing updating the qrcode data using api but it does not generates the qr code.

**Comment by Cordobo** [comment]
I'm having a look into it, thanks for your feedback.

**Comment by usachev-dev** [comment]
Same here

**Comment by gmagaton** [comment]
I made a workaround refreshing page after setting qrcode value.

**Comment by Geschan** [comment]
Same problem here - is there any workarround, without refreshing the page?

**Comment by Cordobo** [comment]
Please update angularx-qrcode to 1.1.6 (Angular 5)

**Comment by Cordobo** [comment]
I uploaded a sample app with a working dynamic update:
https://github.com/Cordobo/angularx-qrcode-sample-app

**Comment by thirupathireddygopal** [comment]
it is not working dynamically when i change the value, at first time when the component instantiate it works but when i change the value dynamically it is not refelecting

**Comment by rahulr-96** [comment]
Any update on this?

**Comment by rahulr-96** [comment]
> Any update on this?

I found a workaround
in html:
` <qrcode *ngIf="downloadUrl" [qrdata]= "downloadUrl" [width]="256" [errorCorrectionLevel]="'M'"></qrcode>`

in ts:
`this.downloadUrl =  url;
 this.cdr.detectChanges();`

**Comment by Joroooo** [comment]
I tried to workaround. 
Does not update it on my side even that i use the string firstly as undefined and i use changeDetectorRef

**Comment by rahulr-96** [comment]
> I tried to workaround.
> Does not update it on my side even that i use the string firstly as undefined and i use changeDetectorRef

Please provide the code that you tried

**Comment by Joroooo** [comment]
Well i fixed. It is being changed now. But the change appears long after the string has changed. Meaning the code is not generated when my string changes but some seconds after it. 

  qrCodeLink: string | undefined = undefined;
isShowingCode = false;


  <qrcode
*ngIf="isShowingCode"
      #qrCodeElement
      [elementType]="'img'"
      id="qr-code"
      [qrdata]="qrCodeLink ?? ''"
      [allowEmptyString]="true"
      [ariaLabel]="xxx"
      [cssClass]="'center'"
      [colorDark]="'#000000ff'"
      [colorLight]="'#ffffffff'"
      [errorCorrectionLevel]="'M'"
      [imageSrc]="'../../../assets/img/logo_symbol.png'"
      [imageHeight]="60"
      [imageWidth]="60"
      [margin]="4"
      [scale]="1"
      [title]="'xxx'"
      [width]="200"
    ></qrcode>

**Comment by EslamKholeef** [comment]
I tried solutions from other planets and nothing worked!
