### ISSUE TITLE
Error: Patch file found for package qrcodejs2 which is not present at node_modules/qrcodejs2

### ISSUE THREAD

**Issue by Goutam192002** [Cordobo/angularx-qrcode#62]
I'm trying to run a script to build my project on a GitLab CI runner....everything worked fine before installing this package. I get the following error when i run 
>npm install

> Error: Patch file found for package qrcodejs2 which is not present at node_modules/qrcodejs2

I'm using the latest version of the package: 1.7.0-beta.5
![Screenshot 2019-11-09 at 6 57 37 PM](https://user-images.githubusercontent.com/33064470/68529321-729f4280-0323-11ea-9b62-8d2f7e8b9843.png)

**Comment by Cordobo** [comment]
Hi and thanks for your reply, the beta should not be used in production, please use version 1.64
