### ISSUE TITLE
missing svg type in v2

### ISSUE THREAD

**Issue by joh-klein** [Cordobo/angularx-qrcode#70]
We loved the old version, because it was possible to output the qr code as svg (and then lossless style it with css). 
Since you are using node-qrcode now this should still[ be possible](https://github.com/soldair/node-qrcode#tostringtext-options-cberror-string) as far as I can tell. 
Are you planing to (re)implement this option?

**Comment by Cordobo** [comment]
Hi @joh-klein 

glad you liked 1.x and I hpe you'll like version 2 the same as it matures. As you said, node-qrcode supports svg. It's on my (internal) road-map but my spare time is kind of limited right now, though PRs are more than welcome :)

**Comment by shoeferlin** [comment]
hey andreas, great package! thanks for that. Also missing the SVG output a bit.

**Comment by Cordobo** [comment]
Hmm, stale-bot and me having a little fight ^^

**Comment by Cordobo** [comment]
SVG support is now available with Version 2.3.0
