### ISSUE TITLE
Support for IE 11

### ISSUE THREAD

**Issue by andreflourenco** [Cordobo/angularx-qrcode#72]
It seems that the component is not supported by IE 11 as it ends up crashing my whole app with the error:

```
SCRIPT1002: Syntax error
vendor.js (159836,20)
```

That error points to the "class" keyword (not supported by IE11) in the following line:

`let QRCodeModule = class QRCodeModule {`

**Comment by Cordobo** [comment]
Hi @andreflourenco 

could you provide me with a stripped-down version of your repo so I can reproduce the error?

**Comment by andreflourenco** [comment]
Hi @Cordobo , I've just tried version 2.1.0 and the error disappeared. Thank you, and sorry for the trouble.
