### ISSUE TITLE
Incompatible with Angular 9.1

### ISSUE THREAD

**Issue by bop10** [Cordobo/angularx-qrcode#75]
The package has incompatible peer dependencies and can't be updated:

```
Package "angularx-qrcode" has an incompatible peer dependency to "@angular/common" (requires ">= 5.0.0 < 9.1.0" (extended), would install "9.1.0").
Package "angularx-qrcode" has an incompatible peer dependency to "@angular/core" (requires ">= 5.0.0 < 9.1.0" (extended), would install "9.1.0").
```

@Cordobo need help with this?

**Comment by Cordobo** [comment]
Hi,

I fixed this issue today in the latest release (2.2.1). A working sample app is available for angular 9.1:

https://github.com/Cordobo/angularx-qrcode-sample-app

For angular 9.x run

`npm install angularx-qrcode@^2.2.1`
or
`yarn addl angularx-qrcode@^2.2.1`
