### ISSUE TITLE
I am not able to deploy in production

### ISSUE THREAD

**Issue by samirmakhani045** [Cordobo/angularx-qrcode#76]
![image](https://user-images.githubusercontent.com/32187273/77652015-9e9a2800-6f93-11ea-843c-ca44627c133c.png)

**Comment by MLuan** [comment]
I'm also having this same issue. 
have you find a solution ?

**Comment by gokselb** [comment]
Same here, trying to troubleshoot.

**Comment by Cordobo** [comment]
Hi there,

I fixed the issue with the latest release (2.2.1). The Readme was updated to reflect the latest changes and a running sample app has been published as well:

https://github.com/Cordobo/angularx-qrcode-sample-app

For angular 9.x run

`npm install angularx-qrcode@^2.2.1`
