### ISSUE TITLE
Installation commands in README.md

### ISSUE THREAD

**Issue by maxtomczyk** [Cordobo/angularx-qrcode#80]
Hi there!

Installation commands in readme looks broken for Angular 8 (and probably 7). As I noticed this package's minor version number is related to desired Angular version.

In my case, installation on Angular 8, following installation command: 
```
npm install angularx-qrcode@^2.1.0 --save
``` 
will install package in version `2.2.1` (which is for Angular 9) and in effect will not work. This happens because of `^` char before version, which accepts minor updates during installation. I think `^` char should be replaced with `~` which will install only patch updates.

**Comment by WillemDockbite** [comment]
Got this error: 
**export 'DEFAULT_CURRENCY_CODE' was not found in '@angular/core'** among other missing exports. Reinstalling the package using `npm install angularx-qrcode@~2.1.0 --save` fixed it for me. 
Thanks @maxtomczyk

**Comment by Cordobo** [comment]
Thanks for opening an issue, fixed!
