### ISSUE TITLE
Use css variables as colorDark or colorLight

### ISSUE THREAD

**Issue by rskendzic** [Cordobo/angularx-qrcode#83]
It would be very useful, especially for white-labelling the app, if there some option to pass `colorDark="var(--color-primary-500)"`

**Comment by Cordobo** [comment]
Hi, sounds like a nice feature. I'm open for contributions and PRs

**Comment by Cordobo** [comment]
Hi @rskendzic 

is this still relevant? What issue did you encounter when you tried passing css vars into those properties?
