### ISSUE TITLE
angularx-qrcode.component.d.ts has some errors

### ISSUE THREAD

**Issue by diegolaisocialcities** [Cordobo/angularx-qrcode#89]
Greetings @Cordobo,

First of all thanks for this plugin, I've found it very helpful!

I have a little problem building my app due errors from angularx-qrcode.component.d.ts, in particular lines 17-18:
    elementType: keyof typeof QRCodeElementType;
    errorCorrectionLevel: keyof typeof QRCodeErrorCorrectionLevel;

CMD and Webstorm, alert about this error with this message: 

TS2475: 'const' enums can only be used in property or index access expressions or the right hand side of an import declaration or export assignment.

EDIT: This error refers to QRCodeElementType and QRCodeErrorCorrectionLevel.

I have a similar error with another plugin, do you have any ideas how to fix this?

Thanks in advance!

**Comment by diegolaisocialcities** [comment]
Hi!

I'm currently using Ionic **3.2.2** (Ionic CLI **5.4.9**). The version of your plugin installed is angularx-qrcode@**2.3.4**.

Actually I didn't understand the "PR against the corresponding branch part", what do you mean? 

Thanks in advance!

**Comment by marciusbezerra** [comment]
try 
npm install angularx-qrcode@1.6.4 --save

**Comment by Cordobo** [comment]
I hope @marciusbezerra comment helped you, I close this issue, please reopne if your issue persists.

**Comment by AnkitMauni** [comment]
@marciusbezerra my angular version is 15.2.6 and i am facing similar error what should i do

**Comment by AnkitMauni** [comment]
when ever i am importing QRCode Module, this error is coming :- "error TS7016: Could not find a declaration file for module 'qrcode'. 'D:/projectname/node_modules/qrcode/lib/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/qrcode` if it exists or add a new declaration (.d.ts) file containing `declare module 'qrcode';`

3 import { QRCodeErrorCorrectionLevel } from "qrcode";
                                             ~~~~~~~~


Error: node_modules/angularx-qrcode/lib/angularx-qrcode.component.d.ts:40:78 - error TS2344: Type '{ allowEmptyString: { alias: "allowEmptyString"; required: false; }; colorDark: { alias: "colorDark"; required: false; }; colorLight: { alias: "colorLight"; required: false; }; cssClass: { alias: "cssClass"; required: false; }; ... 12 more ...; title: { ...; }; }' does not satisfy the constraint '{ [key: string]: string; }'.
  Property '"allowEmptyString"' is incompatible with index signature.
    Type '{ alias: "allowEmptyString"; required: false; }' is not assignable to type 'string'.

40     static ɵcmp: i0.ɵɵComponentDeclaration<QRCodeComponent, "qrcode", never, { "allowEmptyString": { "alias": "allowEmptyString"; "required": false; }; "colorDark": { "alias": "colorDark"; "required": false; }; "colorLight": { "alias": "colorLight"; "required": false; }; "cssClass": { "alias": "cssClass"; "required": false; }; "elementType": { "alias": "elementType"; "required": false; }; "errorCorrectionLevel": { "alias": "errorCorrectionLevel"; "required": false; }; "imageSrc": { "alias": "imageSrc"; "required": false; }; "imageHeight": { "alias": "imageHeight"; "required": false; }; "imageWidth": { "alias": "imageWidth"; "required": false; }; "margin": { "alias": "margin"; "required": false; }; "qrdata": { "alias": "qrdata"; "required": false; }; "scale": { "alias": "scale"; "required": false; }; "version": { "alias": "version"; "required": false; }; "width": { "alias": "width"; "required": false; }; "alt": { "alias": "alt"; "required": false; }; "ariaLabel": { "alias": "ariaLabel"; "required": false; }; "title": { "alias": "title"; "required": false; }; }, { "qrCodeURL": "qrCodeURL"; }, never, never, false, never>;"
