### ISSUE TITLE
incorrect peer dependency with angular 8

### ISSUE THREAD

**Issue by joh-klein** [Cordobo/angularx-qrcode#90]
I am using yarn. And somehow, something changed. I recreated my yarn.lock file, and it is now picking up, that this dependency from you package:

`dependencies: {"@angular/common": ">= 5.0.0 < 9.1.0", … }`

and this one from mine

`dependencies: {"@angular/common": "8.2.14", … }`

can be fulfilled differently than before. It now has two @angular/common references in the lock file, and because of that, it installs a 9.x version of @angular/common under "node_modules/angularx-qrcode/node_modules" and thus I have build errors et al. 

Would it maybe make more sense, to limit the range for the Angular 8.x version to something "< 9.0.0"?

**Comment by joh-klein** [comment]
Since I am on a tight schedule right now, I found a different way to work around this. I added
```json
  "resolutions": {
    "@angular/common": "8.2.14"
  },
```
to my package.json – that helped. I'll try to do a PR, but can't promise anything. Sorry!

**Comment by Cordobo** [comment]
Hi @joh-klein 

I released angularx-qrcode 2.1.3 which should resolve the issue.
