### ISSUE TITLE
Generate qr code in component

### ISSUE THREAD

**Issue by joh-klein** [Cordobo/angularx-qrcode#91]
Is there a way to generate the qr code in a component only? Meaning, that I have a variable that contains the image (base64 encoded) or svg as a string?

**Comment by Cordobo** [comment]
Hi,

do you mind to provide an example? It could be a new usecase worth to implement.

**Comment by joh-klein** [comment]
We have a html page that is generated in the backend, because it consists of two parts (iframes) where the inner part is the angular app but the outer frame is pure html – where a qr code should be visible :)

**Comment by mohsanabbas** [comment]
I am using it to generate PDF but having an issue. it is duplicating qrcode only when it come to printable pdf. in DOM it's all good. I tried canvas, svg but no fix.
